name: Hello World Input Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'Friend'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet user
        run: echo "👋 Hello ${{ github.event.inputs.name }} from GitHub Actions!"
